PACMAN: PACMAN::fp_consts Namespace Reference
PACMAN::fp_consts Namespace Reference
Functions
KOKKOS_INLINE_FUNCTION fp_t min (void)
KOKKOS_INLINE_FUNCTION fp_t max (void)
KOKKOS_INLINE_FUNCTION consteval fp_t zero (void)
KOKKOS_INLINE_FUNCTION consteval fp_t one (void)
KOKKOS_INLINE_FUNCTION consteval fp_t epsilon (void)
auto set_precision (void)
Variables
constexpr unsigned int precision = std::numeric_limits<fp_t>::max_digits10
Function Documentation
epsilon()
KOKKOS_INLINE_FUNCTION consteval fp_t PACMAN::fp_consts::epsilon (void) consteval
Definition at line 98 of file types.hpp.
Referenced by PACMAN::RbfPum::SerialFillQ(), and PACMAN::RbfPum::SerialSVD().
max()
KOKKOS_INLINE_FUNCTION fp_t PACMAN::fp_consts::max (void)
Definition at line 89 of file types.hpp.
Referenced by PACMAN::FiniteElements::ComputeProjectionOn1DSkin(), PACMAN::FiniteElements::ComputeProjectionOn2DSkin(), and PACMAN::RbfPum::SerialDeactivateOneAxis().
min()
KOKKOS_INLINE_FUNCTION fp_t PACMAN::fp_consts::min (void)
Definition at line 85 of file types.hpp.
one()
KOKKOS_INLINE_FUNCTION consteval fp_t PACMAN::fp_consts::one (void) consteval
Definition at line 95 of file types.hpp.
Referenced by PACMAN::FiniteElements::ApplyNewton(), PACMAN::RbfPum::Distance(), PACMAN::RbfPum::WendlandC0::Eval(), PACMAN::RbfPum::WendlandC2::Eval(), PACMAN::RbfPum::WendlandC4::Eval(), PACMAN::RbfPum::WendlandC6::Eval(), PACMAN::RbfPum::WendlandC8::Eval(), PACMAN::RbfPum::SerialFillPoly(), PACMAN::RbfPum::SerialMulMatVec(), PACMAN::RbfPum::SerialSolveQR(), and PACMAN::RbfPum::SquaredDifference().
set_precision()
auto PACMAN::fp_consts::set_precision (void) inline
Definition at line 101 of file types.hpp.
References precision.
Referenced by ArborX::operator<<(), and PACMAN::RbfPum::PrintView().
zero()
KOKKOS_INLINE_FUNCTION consteval fp_t PACMAN::fp_consts::zero (void) consteval
Definition at line 92 of file types.hpp.
Referenced by PACMAN::FiniteElements::ApplyNewton(), PACMAN::RbfPum::Distance(), PACMAN::RbfPum::WendlandC0::Eval(), PACMAN::RbfPum::WendlandC2::Eval(), PACMAN::RbfPum::WendlandC4::Eval(), PACMAN::RbfPum::WendlandC6::Eval(), PACMAN::RbfPum::WendlandC8::Eval(), PACMAN::RbfPum::SerialFillQ(), PACMAN::RbfPum::SerialMulMatVec(), PACMAN::RbfPum::SquaredDifference(), and PACMAN::RbfPum::SquaredDifferenceNoCheck().
Variable Documentation
precision
unsigned int PACMAN::fp_consts::precision = std::numeric_limits<fp_t>::max_digits10 constexpr
Definition at line 100 of file types.hpp.
Referenced by set_precision().